### ISSUE TITLE
[Feature] Opening external links in OS default browser

### ISSUE THREAD

**Issue by BalasivaguruShanmugam** [solitontech/software-practices-metrics-tool#116]
# Description

In this tool, we mostly deals with the PR and branches, to have a detailed look at it we're providing those links in the tool and by clicking it user can navigate to their corresponding service provider link(as of now AzDO). But currently when those URLs are clicked, it gets launched as new electron instance. In this case if user needs to look into multiple PRs, probably they end up with having multiple electron instances opened at a time.

P.S: Even this issue is created from such one electron instance instead of having it opened in browser

## Expected Behavior

External link should be opening as a new tab in the OS default browser.

## Current Behavior

External link is opening as a new electron instance.

## Steps to Reproduce

- Open the desktop application of software practices metrics tool (electron app)
- Go to code review page
- Click on the PR title link
- We can see a new electron instance opened with the PR link

This is applicable for PR link, branch link and even while reporting bug, GitHub issue link will also be opening as electron instance.

## Possible Solution

Using shell module in electron to open the URLs using their default applications.

## Reference

Managing URLs using their default applications - https://www.electronjs.org/docs/latest/api/shell

## Environments

- Node Version: Not Applicable
- NPM Version: Not Applicable
- OS Platform & Version: **Applicable**
- Project Version: Not Applicable
- Version control system: Not Applicable

## Checklist

- [x] This is a new feature request
- [x] This issue has been reproduced in the latest version of the project
- [x] I have searched for similar issues and found none
- [x] This issue is not a duplicate of another issue
- [x] I have provided detailed steps to reproduce
- [x] I have provided expected and actual results
- [x] I have provided a possible solution (optional)

**Comment by ganesh-nithin** [comment]
Thanks for raising your issue Bala. We will add this into our backlog and prioritize accordingly.

**Comment by ganesh-nithin** [comment]
Resolved in #124
